# Generated by Django 3.2 on 2021-04-15 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
